# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-16 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField()),
                ('title', models.CharField(help_text='Enter Survey Title', max_length=200)),
                ('description', models.TextField(help_text='Enter Survey Description', max_length=1000)),
                ('choices', models.FileField(null=True, upload_to='uploads/survey_files')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
