# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-16 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username', max_length=50, unique=True)),
                ('password', models.CharField(help_text='Password', max_length=50)),
            ],
        ),
    ]
