# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-16 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberType', models.CharField(choices=[('RESEARCHER', 'Researcher'), ('SURVEY TAKER', 'Survey Taker'), ('BOTH', 'Both')], help_text='Member Type', max_length=20)),
                ('race', models.CharField(blank=True, choices=[('WHITE', 'White'), ('AFRICAN AMERICAN', 'African American'), ('ASIAN', 'Asian'), ('NATIVE AMERICAN', 'Native American'), ('PACIFIC ISLANDER', 'Pacific Islander')], help_text='Race', max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], help_text='Gender', max_length=20, null=True)),
                ('country', models.CharField(blank=True, help_text='Country', max_length=50, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=50, null=True)),
                ('state', models.CharField(blank=True, help_text='State', max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
